data_dir: "fruit/"
batch_size: 32
learning_rate: 0.0001
num_epochs: 100
random_seed: 43
num_folds: 1
output_dim: 30
cache_images: True
image_size: [64, 64]
validate_every: 10
triplet_margin: 1.0
species_loss_weight: 1.0
segmentation_loss_weight: 1.0
triplet_loss_weight: 1.0